export const posts = [
  {
    name: 'Maria Silva',
    email: 'maria.silva@email.com',
    time: '10 minutos atrás',
    content: 'Hoje concluí o Desafio da Reciclagem! Reciclei todo o papel em casa e me sinto ótima. #Sustentabilidade #Reciclagem',
    active: true,
  },
  {
    name: 'João Santos',
    email: 'joao.santos@email.com',
    time: '1 hora atrás',
    content: 'Compartilhando meu progresso no Curso de Ecologia: aprendi muito sobre conservação da natureza e sustentabilidade. #EducaçãoAmbiental',
    active: false,
  },
  {
    name: 'Fernanda Lima',
    email: 'fernanda.lima@email.com',
    time: '2 horas atrás',
    content: 'Participei do Desafio Dia da Terra plantando árvores no parque local. Vamos cuidar do nosso planeta! 🌍 #DiaDaTerra #AçãoAmbiental',
    active: true,
  },
  {
    name: 'Pedro Oliveira',
    email: 'pedro.oliveira@email.com',
    time: '4 horas atrás',
    content: 'Concluí o Desafio do Dia Sem Carne e adorei as refeições vegetarianas. Reduzir meu impacto ambiental é importante! 🥦 #Sustentabilidade #Vegetarianismo',
    active: true,
  },
  {
    name: 'Ana Ferreira',
    email: 'ana.ferreira@email.com',
    time: '6 horas atrás',
    content: 'Hoje é o Dia Mundial da Biodiversidade. Vamos proteger as espécies em risco e celebrar a diversidade da natureza. 🌿 #Biodiversidade #Conservação',
    active: false,
  },
  {
    name: 'Rafael Rodrigues',
    email: 'rafael.rodrigues@email.com',
    time: '8 horas atrás',
    content: 'Participei do curso online de Energia Sustentável e aprendi a usar energia solar em casa. Economia e sustentabilidade! ☀️ #EnergiaSustentável',
    active: true,
  },
  {
    name: 'Carla Mendes',
    email: 'carla.mendes@email.com',
    time: '10 horas atrás',
    content: 'Adotei o Desafio de Redução de Resíduos e recusei plástico descartável o dia todo. Pequenos gestos fazem a diferença! ♻️ #Sustentabilidade',
    active: false,
  },
  {
    name: 'Luiz Almeida',
    email: 'luiz.almeida@email.com',
    time: '12 horas atrás',
    content: 'Instalei um sistema de coleta de água da chuva em casa. Vamos aproveitar a água da natureza de forma inteligente. 💧 #Água #Sustentabilidade',
    active: true,
  },
  {
    name: 'Isabela Costa',
    email: 'isabela.costa@email.com',
    time: '14 horas atrás',
    content: 'Compartilhando minha experiência de plantar flores no jardim. A natureza é incrível! 🌸 #Jardinagem #Natureza',
    active: true,
  },
  {
    name: 'Miguel Pereira',
    email: 'miguel.pereira@email.com',
    time: '16 horas atrás',
    content: 'Aprendi a fazer sabão caseiro com óleo usado. Redução de resíduos e reciclagem em ação! 🧼 #Sustentabilidade',
    active: false,
  },
  {
    name: 'Larissa Gomes',
    email: 'larissa.gomes@email.com',
    time: '18 horas atrás',
    content: 'Compartilhando dicas para reduzir o desperdício de alimentos. Juntos podemos evitar o desperdício! 🍏 #AlimentaçãoSaudável',
    active: true,
  },
  {
    name: 'Gustavo Santos',
    email: 'gustavo.santos@email.com',
    time: '20 horas atrás',
    content: 'Fechei as janelas durante o dia para aproveitar a luz natural e economizar energia. 💡 #EnergiaSustentável',
    active: true,
  },
  {
    name: 'Camila Lima',
    email: 'camila.lima@email.com',
    time: '22 horas atrás',
    content: 'Limpei a praia durante a minha caminhada matinal. Juntos podemos manter nossas praias limpas! 🏖️ #Preservação',
    active: false,
  },
  {
    name: 'Lucas Pereira',
    email: 'lucas.pereira@email.com',
    time: '1 dia atrás',
    content: 'Instalei lâmpadas de LED em casa e já sinto a diferença na conta de energia. 💡 #Economia',
    active: true,
  },
  {
    name: 'Juliana Alves',
    email: 'juliana.alves@email.com',
    time: '1 dia atrás',
    content: 'Comprei produtos locais para reduzir minha pegada de carbono. Apoiar a comunidade é importante! 🌍 #ConsumoConsciente',
    active: true,
  },
  {
    name: 'Ricardo Silva',
    email: 'ricardo.silva@email.com',
    time: '1 dia atrás',
    content: 'Reciclei todo o vidro da minha casa e entreguei para a reciclagem. Vamos manter o vidro fora dos aterros! ♻️ #Reciclagem',
    active: false,
  },
  {
    name: 'Patrícia Oliveira',
    email: 'patricia.oliveira@email.com',
    time: '1 dia atrás',
    content: 'Plantando árvores com amigos para compensar nossa pegada de carbono. Vamos fazer a diferença! 🌳 #Reflorestamento',
    active: true,
  },
  {
    name: 'Hugo Rodrigues',
    email: 'hugo.rodrigues@email.com',
    time: '2 dias atrás',
    content: 'Economizei água durante o banho hoje e todos os dias. Cada gota conta! 💧 #UsoResponsável',
    active: true,
  },
  {
    name: 'Vanessa Santos',
    email: 'vanessa.santos@email.com',
    time: '2 dias atrás',
    content: 'Recolhi lixo plástico na praia para proteger nossos oceanos. Juntos podemos combater a poluição! 🏖️ #MaresLimpos',
    active: false,
  },
  {
    name: 'Leonardo Costa',
    email: 'leonardo.costa@email.com',
    time: '2 dias atrás',
    content: 'Reduzi meu consumo de carne e descobri pratos vegetarianos deliciosos. Vamos reduzir nossa pegada de carbono! 🥦 #Vegetarianismo',
    active: true,
  },
  {
    name: 'Daniela Almeida',
    email: 'daniela.almeida@email.com',
    time: '3 dias atrás',
    content: 'Reciclei papelão no trabalho e incentivei meus colegas a fazerem o mesmo. Juntos podemos reciclar mais! ♻️ #Reciclagem',
    active: true,
  },
  {
    name: 'Marcos Lima',
    email: 'marcos.lima@email.com',
    time: '3 dias atrás',
    content: 'Fechei as luzes quando saí de casa e reduzi meu consumo de energia. Vamos economizar juntos! 💡 #Economia',
    active: false,
  },
  {
    name: 'Laura Ferreira',
    email: 'laura.ferreira@email.com',
    time: '3 dias atrás',
    content: 'Plantei flores no meu jardim e estou ansiosa para ver as cores da primavera. A natureza é minha inspiração! 🌸 #Jardinagem',
    active: true,
  },
];
